Add `scheduled_time` for Issue1209
MetPX/sarracenia pull request #1210
Opened 2024-09-04 18:22 UTC by andreleblanc11

`scheduled_time` allows us to poll for files when `scheduled_minute`/`scheduled_hour` offers a too broad spectrum of appointments to choose from.

`scheduled_time` should be used when we want to specify specific appointment times when we want to poll/scheduled flow.

2024-09-04 18:31 UTC, petersilva requested changes
*if scheduled_minute and scheduled_hour*
*  means you can use either one alone, have to specify both always.

If somebody specifies times that aren't in ascending order, your method won't work.  need to sort the times before adding them.  Entire appointment list must be in ascending order through the day.

There are unit tests for this module.  You should run them and add new tests with
* one time
* multiple times
* multiple times in wrong order.
* invalid times.

2024-09-04 18:40 UTC, andreleblanc11 commented
Interesting, I thought they came in pairs and you had to specify both. I will change the `and` to a `or` then


> If somebody specifies times that aren't in ascending order, your method won't work. need to sort the times before adding them. Entire appointment list must be in ascending order through the day.

I've added 

https://github.com/MetPX/sarracenia/pull/1210/files#diff-fcf5177e0914e714809f1ff64076b7d252de5e6553b577e6ce6b197105ac6ff8R91

```python3 
self.sched_times.sort()
```

for this. I've made some tests before submitting the PR to validate that it was working

2024-09-04 18:45 UTC, petersilva commented
thinking about it... 
```
>>> import datetime
>>> appointments = [ datetime.time(12,10), datetime.time(15,15), datetime.time(7,7) ]
>>> appointments
[datetime.time(12, 10), datetime.time(15, 15), datetime.time(7, 7)]
>>> appointments.sort()
>>> appointments
[datetime.time(7, 7), datetime.time(12, 10), datetime.time(15, 15)]
>>>

```
so you can just add the appointments to the list and then sort appointments.
You don't need to bother if else making separate lists, just split into hours and minutes and add them to the list, and then sort the result.

maybe less code than you have so far.

2024-09-04 18:53 UTC, andreleblanc11 commented
I think with that logic we can also remove

```
self.hours.sort()
# and
self.minutes.sort()
# in the code
```

2024-09-04 19:25 UTC, andreleblanc11 commented
I also never thought of someone using both options together.. it doesn't hurt to have that option available

2024-09-05 14:00 UTC, andreleblanc11 commented
I've found a bug when trying to use the `default_wait` value. It wasn't using a `datetime.delta` format so I encapsulted it with that and it fixed the problem.

Here's the error we were getting

```
2024-09-05 13:51:05,965 [ERROR] sarracenia.flow gather flowCallback plugin <bound method Scheduled.gather of <sarracenia.flowcb.scheduled.Scheduled object a
t 0x7f34eff24be0>> crashed: '<' not supported between instances of 'int' and 'datetime.timedelta'
2024-09-05 13:51:05,965 [DEBUG] sarracenia.flow gather details:
Traceback (most recent call last):
  File "/net/local/home/leblanca/.local/lib/python3.10/site-packages/sarracenia/flow/__init__.py", line 1133, in gather
    retval = p(self.o.batch-so_far)
  File "/net/local/home/leblanca/.local/lib/python3.10/site-packages/sarracenia/flowcb/scheduled/__init__.py", line 100, in gather
    self.wait_until_next()
  File "/net/local/home/leblanca/.local/lib/python3.10/site-packages/sarracenia/flowcb/scheduled/__init__.py", line 221, in wait_until_next
    self.wait_seconds(self.default_wait)
  File "/net/local/home/leblanca/.local/lib/python3.10/site-packages/sarracenia/flowcb/scheduled/__init__.py", line 140, in wait_seconds
    if sleepfor < nap:
TypeError: '<' not supported between instances of 'int' and 'datetime.timedelta'

```

2024-09-06 03:37 UTC, petersilva commented
I added tests for when one specifies only the minute, or only the hour ... and the current code fails both tests.

2024-09-06 03:46 UTC, petersilva commented
the message being printed out for default interval...:
```
 no scheduled_interval or appointments (combination of scheduled_hour and scheduled_minute) set defaulting to every 0:05:00 seconds

```

* maybe mention schedule_hour/minute/time (no mention of new option in message.)
* 00:05:00 seconds... looks weird.  Not sure what to do about it, but it looks odd.

2024-09-06 18:44 UTC, andreleblanc11 commented
> I added tests for when one specifies only the minute, or only the hour ... and the current code fails both tests.

I think this is expected based on how the code is setup now? If `scheduled_minute` or `scheduled_hour` is not specified, there is no default that is given to resolve the missing option. Maybe we should default to **all of the minutes and all of the hours**  when either option is not specified?

2024-09-06 18:50 UTC, andreleblanc11 commented
> 00:05:00 seconds... looks weird. Not sure what to do about it, but it looks odd.

That's because the default_wait is now in datetime format. Need to change the output to match.

2024-09-06 23:00 UTC, petersilva reviewed
I've seen that bug before... seconds? or total_seconds() ?

2024-09-09 12:16 UTC, andreleblanc11 commented
`seconds` is wrong and `total_seconds` should be used , but it's probably fine to leave it as `default_wait` will never have a changed value.

2024-09-09 22:24 UTC, petersilva approved these changes

2024-09-09 22:24 UTC, merged

2024-09-09 22:26 UTC, petersilva commented
oh darn... I merged it, but we didn't put the slack ("loose") in... so it will still fail.

2024-09-10 11:46 UTC, andreleblanc11 commented
I was going to spawn a different branch for that different issue #1214, and create another PR