Flowcb accept fixes
MetPX/sarracenia pull request #756
Opened 2023-09-01 17:56 UTC by gcglinton

While writing unit tests for all the flowcb/accept plugins, I discovered a number of issues.

- Some (most?) of them lacked an `__ini__` function, which is required to set logging level properly
- Many of them had an improper way of getting/setting config options
  - Added `options.add_option` calls as needed
- Finished porting message structure to v3
  - Propertiesare all just dict keys
  - Some functions are gone
  - the 'headers' key no longer exists
- Added better config validation in some cases
- Fixed numerous logic bugs
- Updating formatting
  - Removing many multi-line statements
  - Fixing indentation of comments

I've consulted with @petersilva and team as much as possible when making these changes, but it's possible some new issues (or regressions, I guess you could say) will be found.

Once this PR is merged, I'll submit a separate PR for these plugins' unit tests.

2023-09-01 18:07 UTC, petersilva requested changes
the fix for *set_notice* is to remove it.  It is not relevant in sr3.

2023-09-01 18:13 UTC, petersilva reviewed
I do not understand the copy.deepcopy(message) in PostOverride... I think we want to override the original have no use for the original, so copying seems pointless.  I could be missing something.

It's a bit strange... not sure it is a blocker though.

2023-09-01 18:19 UTC, petersilva commented on sarracenia/flowcb/accept/tohttp.py
this one is a bit terrifying... we don't know why this logic is here... would prefer to just remove the set_notice
and NOT replace it at all... like in here, there is code where it removes slashes... that is superconfusing in v2,
and it might be a little simpler in v3, but it isn't clear that what the v2 code was doing was "the right thing" ...
just remove all msg["notice"] and callse to set_notice() they are strictly to build v2 messages in v2... they have no relevance to sr3.

2023-09-01 18:21 UTC, petersilva commented on sarracenia/flowcb/filter/wmo2msc.py
this replacement of set_notice is find... just setting the baseUrl and relPath is reasonable.
I feel bad contradicting myself from before... but this is, I think, the only case (fingers crossed) where set_notice needs some translation to sr3.

2023-09-01 18:21 UTC, petersilva commented on sarracenia/flowcb/accept/httptohttps.py
remove msg['set_notice']

2023-09-01 19:09 UTC, gcglinton commented
> I do not understand the copy.deepcopy(message) in PostOverride... I think we want to override the original have no use for the original, so copying seems pointless. I could be missing something.
> 
> It's a bit strange... not sure it is a blocker though.

I'm using `copy.deepcopy` because otherwise, messages appended to `new_incoming` were being modified later on (as those appended messages weren't real copies of the original, but references to them). `deepcopy`ing each message into the `new_incoming` fixed that, and produced what I assumed was the desired behaviour.

2023-09-01 21:24 UTC, petersilva commented
> 
> I'm using `copy.deepcopy` because otherwise, messages appended to `new_incoming` were being modified later on (as those appended messages weren't real copies of the original, but references to them). `deepcopy`ing each message into the `new_incoming` fixed that, and produced what I assumed was the desired behaviour.

Is it possible that you are filling a list with one message in your tests? It is probablynecessary to copy.deepcopy when putting the messages in the list in the first place. with real data, the situation you describe is a problem that should not occur.

but if that's really happenning, then the copy.deepcopy should happen somewhere far upstream.  Either way it does not make sense to have it where it is.

2023-09-05 14:56 UTC, gcglinton commented
Per discussion with Peter, the changes to make are:
- `tohttp` should *just* swap out whatever scheme is in baseURL to be http
- In `postoverride`
  - Don't append to new_incoming, just work on the messages themselves
- In all changes, don't do anything with `message['headers'][<thing>]`, do things directly on `message[<thing>]`
- 
@petersilva, does this seem right?

2023-09-06 17:22 UTC, petersilva approved these changes

2023-09-06 17:24 UTC, merged